language: python
python:
  - '3.6.5'
node_js: '0.8'

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install pipenv
  - pipenv install --skip-lock
  - npm install
  - PATH=$PATH:$(pwd)/node_modules/.bin

script:
  - inv lint-js
  - pytest --cov=backend/ && coverage report

after_success:
- coveralls
